services:
    facturex-tomcat:
        build:
            context: ./tomcat
        container_name: facturex-tomcat
        restart: always
        ports:
            - "8080:8080"
        networks:
            - snet
        depends_on:
            - "facturex-database"
        volumes:
            - ./war:/usr/local/tomcat/webapps
            - ./logs/server:/usr/local/tomcat/logs
            - ./logs/apps:/opt/tomcat/logs
            - ./apk:/opt/apk

    facturex-database:
        build: 
            context: ./database
        restart: always
        ports: 
            - "5432:5432"
        container_name: facturex-postgres
        environment:
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=root
           - POSTGRES_DB=postgres
           - POSTGRES_HOST=facturex-database
           - POSTGRES_MULTIPLE_DATABASES=faturex_db
        networks:
            - snet
        volumes:
            - db_data:/opt/postgres/data
    facturex-web:
        build: 
            context: ./nginx
        restart: always
        container_name: facturex-web
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "facturex-tomcat"
        volumes:
            - ./nginx:/etc/nginx/
           # - ./data/certbot/conf:/etc/letsencrypt:ro
           # - ./data/certbot/www:/var/www/certbot:ro
       # command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - snet
   # facturex-certbot:
   #     container_name: facturex-certbot
   #     build:
   #         context: ./certbot
   #     volumes:
   #         - ./data/certbot/conf:/etc/letsencrypt
   #         - ./data/certbot/www:/var/www/certbot
        # This script keeps the container alive and checks for renewals every 12 hours
   #     command: "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
   #     networks:
   #         - snet
networks:
    snet:

volumes:
    db_data: