services:
    faturex-tomcat:
        build:
            context: ./tomcat
        container_name: faturex-tomcat
        restart: always
        ports:
            - "8080:8080"
        networks:
            - snet
        depends_on:
            - "faturex-database"
        volumes:
            - ./war:/usr/local/tomcat/webapps
            - ./logs/server:/usr/local/tomcat/logs
            - ./logs/apps:/opt/tomcat/logs
            - ./apk:/opt/apk

    faturex-database:
        build: 
            context: ./database
        restart: always
        ports: 
            - "5432:5432"
        container_name: faturex-postgres
        environment:
           - POSTGRES_USER=postgres
           - POSTGRES_PASSWORD=root
           - POSTGRES_DB=postgres
           - POSTGRES_HOST=faturex-database
           - POSTGRES_MULTIPLE_DATABASES=faturex_db
        networks:
            - snet
        volumes:
            - db_data:/opt/postgres/data
    faturex-web:
        build: 
            context: ./nginx
        restart: always
        container_name: faturex-web
        ports:
            - "80:80"
            - "443:443"
        depends_on:
            - "faturex-tomcat"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./data/certbot/conf:/etc/letsencrypt:ro
            - ./data/certbot/www:/var/www/certbot:ro
        command: "/bin/sh -c 'while :; do sleep 12h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
        networks:
            - snet
    faturex-certbot:
        container_name: faturex-certbot
        build:
            context: ./certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        # This script keeps the container alive and checks for renewals every 12 hours
        command: "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
        networks:
            - snet
networks:
    snet:

volumes:
    db_data: