max_connections = 200
shared_buffers = 3200MB
work_mem = 512MB
maintenance_work_mem = 512MB
effective_cache_size = 8000MB
checkpoint_completion_target = 0.8
synchronous_commit = off
max_locks_per_transaction = 1024
wall_writer_delay = 10000ms
random_page_cost = 1.1
max_wal_size = 16GB
min_wal_size = 4GB
listen_addresses = '*'
dynamic_shared_memory_type = posix
log_timezone = 'Africa/Maputo'
timezone = 'Africa/Maputo'

