worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include mime.types;
    default_type application/octet-stream;
    server {
        listen 80;
		server_name mozzapp.online;

		# Redirect all HTTP requests to HTTPS
        location / {
           return 301 https://$host$request_uri;
        }

    }
    server {
        listen 443 ssl;
		server_name mozzapp.online;

        root /usr/share/nginx/html;

		client_max_body_size 10M;

		ssl_certificate      /etc/letsencrypt/live/mozzapp.online/fullchain.pem;
		ssl_certificate_key  /etc/letsencrypt/live/mozzapp.online/privkey.pem;

        gzip on;
        gzip_min_length 100;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload" always;
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-Content-Type-Options "nosniff";

        location / {
 	      add_header Allow 'GET, POST, PUT, PATCH, DELETE' always;
          add_header 'Access-Control-Allow-Origin' '*' always;
          add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, PATCH, DELETE, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
          add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;

            try_files $uri $uri/ /index.html;
        }


	location /faturex {
            proxy_pass http://s-tomcat:8080/faturex;

	        proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_set_header   X-Forwarded-Proto $scheme; # Tells Tomcat the original request was HTTPS
        }

    }
}