worker_processes  1;

events {
    worker_connections  1024;
}

http {

    server {
        listen 80;
		server_name mozzapp.online;

        root /usr/share/nginx/html;

		client_max_body_size 10M;

        gzip on;
        gzip_min_length 100;
        gzip_proxied expired no-cache no-store private auth;
        gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript;

        location / {
 	  add_header Allow 'GET, POST, PUT, PATCH, DELETE' always;
          add_header 'Access-Control-Allow-Origin' '*' always;
          add_header 'Access-Control-Allow-Methods' 'GET, PUT, POST, PATCH, DELETE, OPTIONS' always;
          add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
          add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
          add_header 'Access-Control-Allow-Credentials' 'true' always;

            try_files $uri $uri/ /index.html;
        }


	location /faturex {
            proxy_pass http://s-tomcat:8080/faturex;

	    proxy_redirect     off;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
        }

    }
}